backend:
  name: git-gateway
  branch: main  # Cambia "main" si usas otra rama principal

media_folder: "static/images/uploads"  # Carpeta donde se guardarán los archivos subidos
public_folder: "/images/uploads"       # Ruta pública para esos archivos

collections:
  - name: "posts"             # Nombre de la colección
    label: "Posts"            # Etiqueta que se verá en la UI de Decap CMS
    folder: "content/posts"   # Carpeta donde se guardarán los posts
    create: true
    slug: "{{slug}}"          # Usado para generar URLs
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }