backend:
  name: git-gateway
  branch: main

<<<<<<< HEAD
media_folder: /images          # Carpeta donde se guardan las imágenes en el repositorio
public_folder: /images              # Ruta pública para acceder a las imágenes
=======
media_folder: static/img          # Carpeta donde se guardan las imágenes en el repositorio
public_folder: static/img            # Ruta pública para acceder a las imágenes
>>>>>>> 8c5c8a9e48211abf0cea84389b5e669bbddfbd68

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Post"
    folder: "src/pages/blog"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"} # Imagen destacada para el post
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "products"
    label: "Products"
    label_singular: "Product"
    folder: "src/pages/products"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page.template"}
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}                 # Imagen del producto
      - {label: "Gallery", name: "gallery", widget: "list", field: {label: "Image", name: "image", widget: "image"}} # Galería de imágenes
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Ingredients", name: "ingredients", widget: "list"}

  - name: "miembros"
    label: "Miembros"
    label_singular: "Post Miembro"
    folder: "src/pages/miembros"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "miembros-post.template"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featuredImage", widget: "image"} # Imagen destacada para el post
      - {label: "Body", name: "body", widget: "markdown"}